	--Broken Parts
	["broken_axel"]=          {["name"] = "broken_axel",        ["label"] = "Broken Axel",			["weight"] = 0, ["type"] = "item",  ["image"] = "broken_axel.png",        ["unique"] = true,  ["useable"] = false,["shouldClose"] = false,["description"] = ""},
	["broken_brake_caliper"]=          {["name"] = "broken_brake_caliper",        ["label"] = "Broken Caliper",			["weight"] = 0, ["type"] = "item",  ["image"] = "broken_brake_caliper.png",        ["unique"] = true,  ["useable"] = false,["shouldClose"] = false,["description"] = ""},
	["broken_brakedisc"]=          {["name"] = "broken_brakedisc",        ["label"] = "Broken Disc",			["weight"] = 0, ["type"] = "item",  ["image"] = "Broken_brakedisc.png",        ["unique"] = true,  ["useable"] = false,["shouldClose"] = false,["description"] = ""},
	["broken_engineblock"]=          {["name"] = "broken_engineblock",        ["label"] = "Broken Engine Block",			["weight"] = 0, ["type"] = "item",  ["image"] = "broken_engineblock.png",        ["unique"] = true,  ["useable"] = false,["shouldClose"] = false,["description"] = ""},
	["broken_manifold"]=          {["name"] = "broken_manifold",        ["label"] = "Broken Manifold",			["weight"] = 0, ["type"] = "item",  ["image"] = "broken_manifold.png",        ["unique"] = true,  ["useable"] = false,["shouldClose"] = false,["description"] = ""},
	["broken_piston"]=          {["name"] = "broken_piston",        ["label"] = "Broken Piston",			["weight"] = 0, ["type"] = "item",  ["image"] = "broken_piston.png",        ["unique"] = true,  ["useable"] = false,["shouldClose"] = false,["description"] = ""},
	["broken_rim"]=          {["name"] = "broken_rim",        ["label"] = "Broken Rim",			["weight"] = 0, ["type"] = "item",  ["image"] = "broken_rim.png",        ["unique"] = true,  ["useable"] = false,["shouldClose"] = false,["description"] = ""},
	["broken_suspension"]=          {["name"] = "broken_suspension",        ["label"] = "Broken Suspension",			["weight"] = 0, ["type"] = "item",  ["image"] = "broken_suspension.png",        ["unique"] = true,  ["useable"] = false,["shouldClose"] = false,["description"] = ""},
	["broken_suspension_arm"]=          {["name"] = "broken_suspension_arm",        ["label"] = "Broken Suspension Arm",			["weight"] = 0, ["type"] = "item",  ["image"] = "broken_suspension_arm.png",        ["unique"] = true,  ["useable"] = false,["shouldClose"] = false,["description"] = ""},
	["broken_tire"]=          {["name"] = "broken_tire",        ["label"] = "Broken Tire",			["weight"] = 0, ["type"] = "item",  ["image"] = "broken_tire.png",        ["unique"] = true,  ["useable"] = false,["shouldClose"] = false,["description"] = ""},
	["broken_transmission"]=          {["name"] = "broken_transmission",        ["label"] = "Broken Transmission",			["weight"] = 0, ["type"] = "item",  ["image"] = "broken_transmission.png",        ["unique"] = true,  ["useable"] = false,["shouldClose"] = false,["description"] = ""},
	["broken_transmission_cylinder"]=          {["name"] = "broken_transmission_cylinder",        ["label"] = "Broken Cylinder",			["weight"] = 0, ["type"] = "item",  ["image"] = "broken_transmission.png",        ["unique"] = true,  ["useable"] = false,["shouldClose"] = false,["description"] = ""},
		